FROM mysql:5.7.28

COPY entry.sh /entry.sh
COPY key/db2 /root/.ssh
COPY package/mha4mysql-node_0.54-0_all.deb /tmp/mha4mysql-node.deb
COPY conf/mysql2.cnf /etc/mysql/conf.d/mysql.cnf

RUN apt-get update && \
    apt-get install -y  bash git openssh-server rsync augeas-tools libdbd-mysql-perl && \
    deluser $(getent passwd 33 | cut -d: -f1) && \
    delgroup $(getent group 33 | cut -d: -f1) 2>/dev/null || true && \
    mkdir -p /root/.ssh && chmod 700 /root/.ssh/ &&\
    augtool 'set /files/etc/ssh/sshd_config/PermitRootLogin "yes"' && \
    augtool 'set /files/etc/ssh/sshd_config/AuthorizedKeysFile ".ssh/authorized_keys .ssh/authorized_keys2"' && \
    augtool 'set /files/etc/ssh/sshd_config/PermitEmptyPasswords "yes"' && \
    echo "    StrictHostKeyChecking no" >> /etc/ssh/ssh_config && \
    echo "    UserKnownHostsFile /dev/null" >> /etc/ssh/ssh_config && \
    mkdir -p /var/log/masterha/ && \
    dpkg -i /tmp/mha4mysql-node.deb
 
EXPOSE 22 3306

ENTRYPOINT ["/entry.sh"]
