FROM mysql:5.7.28

COPY package/mha4mysql-node_0.54-0_all.deb /tmp/mha4mysql-node.deb

RUN apt-get update && \
    apt-get install -y  bash git openssh-server rsync augeas-tools libdbd-mysql-perl && \
    deluser $(getent passwd 33 | cut -d: -f1) && \
    delgroup $(getent group 33 | cut -d: -f1) 2>/dev/null || true && \
    mkdir -p /root/.ssh && chmod 700 /root/.ssh/ &&\
    augtool 'set /files/etc/ssh/sshd_config/PermitRootLogin "yes"' && \
    augtool 'set /files/etc/ssh/sshd_config/AuthorizedKeysFile ".ssh/authorized_keys .ssh/authorized_keys2"' && \
    augtool 'set /files/etc/ssh/sshd_config/PermitEmptyPasswords "yes"' && \
    echo "    StrictHostKeyChecking no" >> /etc/ssh/ssh_config && \
    echo "    UserKnownHostsFile /dev/null" >> /etc/ssh/ssh_config && \
    mkdir -p /var/log/masterha/ && \
    dpkg -i /tmp/mha4mysql-node.deb

ARG SERVICE_N
ARG F_NUM

COPY entry.sh /entry.sh
COPY conf/${SERVICE_N}/key /root/.ssh
COPY conf/common/mysql${F_NUM}.cnf /etc/mysql/conf.d/mysql.cnf

RUN chmod 775 /entry.sh && \
    chmod 644 /root/.ssh/authorized_keys && \
    chmod 644 /root/.ssh/id_rsa.pub && \
    chmod 600 /root/.ssh/id_rsa

EXPOSE 22 3306

ENTRYPOINT ["/entry.sh"]
